using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BestFor.Domain.Entities
{
    /// <summary>
    /// Represents a string in some language. Used for localization.
    /// </summary>
    public class ResourceString : EntityBase
    {
        /// <summary>
        /// Autogenerated database identity Id. Not quite used
        /// </summary>
        [Key, Required, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public override int Id { get; set; }

        /// <summary>
        /// Unique string name. Example "Site Title".
        /// </summary>
        [Required]
        public string Key { get; set; }

        /// <summary>
        /// Name of the culture the string is for. Example en-US
        /// </summary>
        [Required]
        public string CultureName { get; set; }

        /// <summary>
        /// Value in this language.
        /// </summary>
        [Required]
        public string Value { get; set; }
    }
}
